### ISSUE TITLE
In automation: when two target semantic elements are set by one business Element.

### ISSUE THREAD

**Issue by KenLord** [MDMI/cda2mdmi#9] opened 2015-09-09 13:52 UTC
For example, medication activity can be a prescription, dispense, or administration.  In ccda, it is determined by the moodcode assignment.  However, the Business Element of MedicationPrescription Container implies the setting of the correct moodCode.  

For our automation of CCDA and perhaps other formats MDMI maps, we should have an approach to resolve this issue.

**Comment by swmuir** [comment] 2015-12-14 14:24
Duplicate of mood code

**Closed by swmuir** 2015-12-14 14:24 UTC
Labels: enhancement
